// Stage 9 — the gallery: albums, images and room-type covers.
//
// No production photography is copied. Every image is generated by
// lib/placeholder-image.mjs as a brand-coloured gradient, uploaded to the
// private gallery-images bucket on the application's own path convention
// ({property}/{image}-{file} and {property}/thumbnails/{image}-{file}), and
// registered with a real gallery_images row — so signed URLs, thumbnails,
// covers and the public booking pages all resolve exactly as they would with
// real photographs, and replacing them later is a straight swap.

import { randomUUID } from "node:crypto";
import { gradientPng } from "../lib/placeholder-image.mjs";
import { ensureByKey } from "../lib/env.mjs";

const BRAND = { navy: [27, 58, 92], gold: [200, 169, 81], sand: [242, 236, 226], slate: [47, 72, 88] };

const ALBUMS = [
  { name: "Rooms & Suites", description: "Every room type at Infinity Grand Hotel", sort_order: 1 },
  { name: "Restaurant & Bar", description: "The Grand Restaurant and Skyline Bar", sort_order: 2 },
  { name: "Facilities", description: "Pool, gym, meetings and the lobby", sort_order: 3 },
];

const FACILITY_IMAGES = [
  { context: "hotel", title: "Lobby at dusk", caption: "The double-height lobby, looking towards Independence Avenue.", album: "Facilities", from: BRAND.navy, to: BRAND.slate },
  { context: "hotel", title: "Hotel frontage", caption: "Infinity Grand Hotel, Airport Residential Area, Accra.", album: "Facilities", from: BRAND.slate, to: BRAND.navy },
  { context: "restaurant", title: "The Grand Restaurant", caption: "Breakfast service, ground floor.", album: "Restaurant & Bar", from: BRAND.gold, to: BRAND.navy },
  { context: "restaurant", title: "Private dining room", caption: "Seats fourteen, available for corporate lunches.", album: "Restaurant & Bar", from: BRAND.sand, to: BRAND.gold },
  { context: "bar", title: "Skyline Bar", caption: "Rooftop bar, open from 17:00.", album: "Restaurant & Bar", from: BRAND.navy, to: BRAND.gold },
  { context: "swimming_pool", title: "Pool deck", caption: "Heated pool and loungers on the fourth floor.", album: "Facilities", from: BRAND.sand, to: BRAND.navy },
  { context: "gym", title: "Fitness centre", caption: "Open 24 hours to resident guests.", album: "Facilities", from: BRAND.slate, to: BRAND.sand },
  { context: "facility", title: "Meeting room — Volta", caption: "Boardroom for twelve with full AV.", album: "Facilities", from: BRAND.gold, to: BRAND.slate },
];

export async function run({ ctx, admin, log }) {
  const pid = ctx.propertyId;
  if (ctx.dryRun) {
    log(`  · would create ${ALBUMS.length} albums and generate room-type and facility images`);
    return {};
  }

  const albums = await ensureByKey(
    admin, "gallery_albums", `select=*&property_id=eq.${pid}`,
    ALBUMS.map((a) => ({ ...a, property_id: pid, created_by: admin.userId })), (r) => r.name,
  );
  const albumByName = new Map(albums.rows.map((a) => [a.name, a]));
  log(`  · albums: ${albums.created} created, ${albums.existing} already present`);

  const roomTypes = await admin.select("room_types", `select=id,code,name&property_id=eq.${pid}&order=base_rate.asc`);
  const existingImages = await admin.select("gallery_images", `select=id,title,room_type_id,context&property_id=eq.${pid}&limit=200`);
  const haveTitle = new Set(existingImages.map((i) => i.title));

  const palette = [
    [BRAND.navy, BRAND.slate], [BRAND.slate, BRAND.gold], [BRAND.gold, BRAND.sand],
    [BRAND.sand, BRAND.navy], [BRAND.navy, BRAND.gold], [BRAND.slate, BRAND.sand],
  ];

  const uploads = [];
  roomTypes.forEach((type, index) => {
    for (const [variant, label] of [["", ""], ["-2", " — second view"]]) {
      uploads.push({
        title: `${type.name}${label}`,
        caption: `${type.name} at Infinity Grand Hotel.`,
        context: "room_type",
        room_type_id: type.id,
        album: "Rooms & Suites",
        from: palette[index % palette.length][0],
        to: palette[index % palette.length][1],
        isCover: variant === "",
        fileName: `${type.code.toLowerCase()}${variant}.png`,
        seed: index + (variant ? 3 : 1),
      });
    }
  });
  FACILITY_IMAGES.forEach((image, index) => {
    uploads.push({
      ...image,
      room_type_id: null,
      isCover: false,
      fileName: `${image.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.png`,
      seed: index + 11,
    });
  });

  let created = 0;
  let failed = 0;
  const covers = [];
  for (const image of uploads) {
    if (haveTitle.has(image.title)) continue;
    const imageId = randomUUID();
    const full = gradientPng({ width: 1600, height: 1067, from: image.from, to: image.to, accent: [255, 250, 240], seed: image.seed });
    const thumb = gradientPng({ width: 480, height: 320, from: image.from, to: image.to, accent: [255, 250, 240], seed: image.seed });
    const storagePath = `${pid}/${imageId}-${image.fileName}`;
    const thumbnailPath = `${pid}/thumbnails/${imageId}-${image.fileName}`;

    const a = await admin.upload("gallery-images", storagePath, full, "image/png");
    const b = await admin.upload("gallery-images", thumbnailPath, thumb, "image/png");
    if (!a.ok || !b.ok) {
      failed++;
      if (failed === 1) log(`  ! gallery upload: ${a.status} ${a.body} / ${b.status} ${b.body}`);
      continue;
    }
    const [row] = await admin.insert("gallery_images", [{
      id: imageId,
      property_id: pid,
      album_id: albumByName.get(image.album)?.id ?? null,
      context: image.context,
      room_type_id: image.room_type_id,
      title: image.title,
      caption: image.caption,
      storage_path: storagePath,
      thumbnail_path: thumbnailPath,
      is_cover: false,
      sort_order: created,
      active: true,
      uploaded_by: admin.userId,
    }]);
    created++;
    if (image.isCover && image.room_type_id) covers.push({ roomTypeId: image.room_type_id, imageId: row.id });
  }
  log(`  · images: ${created} generated and uploaded${failed ? `, ${failed} failed` : ""}`);

  // Covers are set through the RPC, which also clears any previous cover.
  let coversSet = 0;
  for (const cover of covers) {
    const r = await admin.tryRpc("set_gallery_room_type_cover", {
      _property_id: pid, _room_type_id: cover.roomTypeId, _image_id: cover.imageId,
    });
    if (r.ok) coversSet++;
    else if (coversSet === 0) log(`  ! set_gallery_room_type_cover: ${JSON.stringify(r.body).slice(0, 200)}`);
  }
  log(`  · room-type covers set: ${coversSet}`);

  return {};
}
