import type { AppRole } from "@/hooks/use-user-roles";
import type { PermissionCapability } from "@/lib/permissions";

export const HRM_ADMIN_ROLES: readonly AppRole[] = [
  "super_admin",
  "hotel_owner",
  "general_manager",
  "hr",
];

export const PAYROLL_SENSITIVE_ROLES: readonly AppRole[] = ["super_admin", "hotel_owner", "hr"];

export const HRM_PERMISSIONS = {
  dashboardView: { module: "hrm_dashboard", capability: "view" },
  employeeView: { module: "employees", capability: "view" },
  employeeCreate: { module: "employees", capability: "create" },
  employeeEdit: { module: "employees", capability: "edit" },
  employeeArchive: { module: "employees", capability: "delete_or_archive" },
  employeeRestore: { module: "employees", capability: "delete_or_archive" },
  sensitiveEmployeeView: { module: "employees_sensitive", capability: "view" },
  departmentView: { module: "departments", capability: "view" },
  departmentManage: { module: "departments", capability: "manage_settings" },
  designationView: { module: "designations", capability: "view" },
  designationManage: { module: "designations", capability: "manage_settings" },
  documentView: { module: "employee_documents", capability: "view" },
  documentUpload: { module: "employee_documents", capability: "create" },
  documentEdit: { module: "employee_documents", capability: "edit" },
  documentArchive: { module: "employee_documents", capability: "delete_or_archive" },
  confidentialDocumentView: {
    module: "confidential_employee_documents",
    capability: "view",
  },
  announcementView: { module: "staff_announcements", capability: "view" },
  announcementManage: { module: "staff_announcements", capability: "manage_settings" },
  announcementPublish: { module: "staff_announcements", capability: "approve" },
  workforceSettingsView: { module: "workforce_settings", capability: "view" },
  workforceSettingsManage: {
    module: "workforce_settings",
    capability: "manage_settings",
  },
  shiftView: { module: "shift_templates", capability: "view" },
  shiftManage: { module: "shift_templates", capability: "manage_settings" },
  rosterView: { module: "duty_roster", capability: "view" },
  rosterManage: { module: "duty_roster", capability: "manage_settings" },
  rosterPublish: { module: "duty_roster", capability: "approve" },
  holidayView: { module: "holidays", capability: "view" },
  holidayManage: { module: "holidays", capability: "manage_settings" },
  attendanceView: { module: "attendance", capability: "view" },
  attendanceCreate: { module: "attendance", capability: "create" },
  attendanceEdit: { module: "attendance", capability: "edit" },
  attendanceApprove: { module: "attendance", capability: "approve" },
  attendanceExport: { module: "attendance", capability: "export" },
  attendancePrint: { module: "attendance", capability: "print" },
  ownAttendanceView: { module: "attendance_own", capability: "view" },
  ownTimeClockUse: { module: "time_clock", capability: "view" },
  attendanceEventsView: { module: "attendance_events", capability: "view" },
  attendanceAdjustmentView: { module: "attendance_adjustments", capability: "view" },
  attendanceAdjustmentCreate: {
    module: "attendance_adjustments",
    capability: "create",
  },
  attendanceAdjustmentApprove: {
    module: "attendance_adjustments",
    capability: "approve",
  },
  ownLeaveView: { module: "leave_own", capability: "view" },
  ownLeaveCreate: { module: "leave_own", capability: "create" },
  ownLeaveWithdraw: { module: "leave_own", capability: "edit" },
  teamLeaveView: { module: "leave_team", capability: "view" },
  propertyLeaveView: { module: "leave_property", capability: "view" },
  leaveApprove: { module: "leave", capability: "approve" },
  leaveCancel: { module: "leave", capability: "delete_or_archive" },
  leaveSettingsView: { module: "leave_settings", capability: "view" },
  leaveSettingsManage: { module: "leave_settings", capability: "manage_settings" },
  leaveBalancesView: { module: "leave_balances", capability: "view" },
  leaveBalancesAdjust: { module: "leave_balances", capability: "manage_settings" },
  leaveCalendarView: { module: "leave_calendar", capability: "view" },
  leaveDocumentsView: { module: "leave_documents", capability: "view" },
  biometricDevicesView: { module: "biometric_devices", capability: "view" },
  biometricDevicesManage: { module: "biometric_devices", capability: "manage_settings" },
  biometricMappingsManage: { module: "biometric_mappings", capability: "manage_settings" },
  biometricEventsImport: { module: "biometric_events", capability: "create" },
  biometricEventsReview: { module: "biometric_events", capability: "view" },
  payrollOverviewView: { module: "payroll_overview", capability: "view" },
  payrollSettingsView: { module: "payroll_settings", capability: "view" },
  payrollSettingsManage: { module: "payroll_settings", capability: "manage_settings" },
  payCalendarsView: { module: "pay_calendars", capability: "view" },
  payCalendarsManage: { module: "pay_calendars", capability: "manage_settings" },
  salaryStructuresView: { module: "salary_structures", capability: "view" },
  salaryStructuresManage: { module: "salary_structures", capability: "manage_settings" },
  payComponentsView: { module: "pay_components", capability: "view" },
  payComponentsManage: { module: "pay_components", capability: "manage_settings" },
  employeeCompensationView: { module: "employee_compensation", capability: "view" },
  employeeCompensationManage: {
    module: "employee_compensation",
    capability: "manage_settings",
  },
  sensitiveCompensationView: {
    module: "employee_compensation_sensitive",
    capability: "view",
  },
  paymentDetailsView: { module: "payment_details", capability: "view" },
  paymentDetailsManage: { module: "payment_details", capability: "manage_settings" },
  fullPaymentDetailsReveal: { module: "payment_details_full", capability: "view" },
  paymentDetailsVerify: { module: "payment_details", capability: "approve" },
  statutoryRulesView: { module: "statutory_rules", capability: "view" },
  statutoryRulesManage: { module: "statutory_rules", capability: "manage_settings" },
  openingBalancesView: { module: "opening_balances", capability: "view" },
  openingBalancesImport: { module: "opening_balances", capability: "create" },
  openingBalancesManage: { module: "opening_balances", capability: "manage_settings" },
  payrollRunsView: { module: "payroll_runs", capability: "view" },
  payrollRunsCreate: { module: "payroll_runs", capability: "create" },
  payrollRunsCalculate: { module: "payroll_run_calculate", capability: "create" },
  payrollRunsRecalculate: { module: "payroll_run_recalculate", capability: "manage_settings" },
  payrollRunsLock: { module: "payroll_run_lock", capability: "approve" },
  payrollRunsReopen: { module: "payroll_run_reopen", capability: "manage_settings" },
  payrollRunsArchive: { module: "payroll_run_archive", capability: "delete_or_archive" },
  payrollEmployeeResultsView: { module: "payroll_employee_results", capability: "view" },
  payrollCalculationDetailsView: { module: "payroll_calculation_details", capability: "view" },
  payrollManualInputsView: { module: "payroll_manual_inputs", capability: "view" },
  payrollManualInputsManage: { module: "payroll_manual_inputs", capability: "manage_settings" },
  payrollValidationsView: { module: "payroll_validations", capability: "view" },
  payrollWarningsAcknowledge: { module: "payroll_warnings", capability: "approve" },
  payrollDraftExport: { module: "payroll_draft_reports", capability: "export" },
  payrollDraftPrint: { module: "payroll_draft_reports", capability: "print" },
  payrollApprovalSubmit: { module: "payroll_approvals", capability: "create" },
  payrollApprovalView: { module: "payroll_approvals", capability: "view" },
  payrollApprovalApprove: { module: "payroll_approvals", capability: "approve" },
  payrollApprovalReject: { module: "payroll_approvals", capability: "delete_or_archive" },
  payrollFinalizationExecute: { module: "payroll_finalization", capability: "approve" },
  finalizedPayrollView: { module: "finalized_payroll", capability: "view" },
  finalizedPayrollSensitiveView: { module: "finalized_payroll_sensitive", capability: "view" },
  payslipGenerate: { module: "payslips", capability: "create" },
  payslipPublish: { module: "payslips", capability: "approve" },
  payslipUnpublish: { module: "payslips", capability: "delete_or_archive" },
  ownPayslipView: { module: "payslips_own", capability: "view" },
  payslipDownload: { module: "payslip_downloads", capability: "view" },
  paymentBatchesView: { module: "payroll_payment_batches", capability: "view" },
  paymentBatchesPrepare: { module: "payroll_payment_batches", capability: "create" },
  paymentBatchesValidate: { module: "payroll_payment_batches", capability: "approve" },
  paymentExportGenerate: { module: "payroll_payment_exports", capability: "export" },
  paymentExportSensitiveFields: {
    module: "payroll_payment_export_sensitive",
    capability: "export",
  },
  paymentTemplatesView: { module: "payroll_payment_templates", capability: "view" },
  paymentTemplatesManage: { module: "payroll_payment_templates", capability: "manage_settings" },
  statutoryLiabilitiesView: { module: "payroll_statutory_liabilities", capability: "view" },
  statutoryLiabilitiesExport: { module: "payroll_statutory_liabilities", capability: "export" },
  journalMappingsView: { module: "payroll_journal_mappings", capability: "view" },
  journalMappingsManage: { module: "payroll_journal_mappings", capability: "manage_settings" },
  journalDraftsView: { module: "payroll_journal_drafts", capability: "view" },
  journalDraftsGenerate: { module: "payroll_journal_drafts", capability: "create" },
  journalDraftsExport: { module: "payroll_journal_drafts", capability: "export" },
  payrollPeriodClose: { module: "payroll_period_close", capability: "approve" },
  payrollPeriodReopen: { module: "payroll_period_reopen", capability: "manage_settings" },
  payrollCorrectionCreate: { module: "payroll_corrections", capability: "create" },
  payrollCorrectionApprove: { module: "payroll_corrections", capability: "approve" },
  payrollReversalExecute: { module: "payroll_reversals", capability: "approve" },
  supplementalPayrollCreate: { module: "supplemental_payroll", capability: "create" },
  finalizedPayrollExport: { module: "finalized_payroll_reports", capability: "export" },
  finalizedPayrollPrint: { module: "finalized_payroll_reports", capability: "print" },
} as const satisfies Record<string, { module: string; capability: PermissionCapability }>;
