/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { assuranceLevelFromClaims, requiresMfa } from "@/lib/security/mfa-policy";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function authMiddleware(options: { allowPasswordChange: boolean; allowAal1: boolean }) {
  return createMiddleware({ type: "function" }).server(async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    const { data: profile, error: profileError } = (await supabase
      .from("profiles")
      .select("status,must_change_password")
      .eq("id", data.claims.sub)
      .single()) as any;
    if (profileError || !profile || profile.status !== "active") throw new Error("Unauthorized");
    if (!options.allowPasswordChange && profile.must_change_password)
      throw new Error("Password change required");

    const { data: roleRows, error: rolesError } = (await supabase
      .from("user_roles")
      .select("role")
      .eq("user_id", data.claims.sub)) as any;
    if (rolesError) throw new Error("Unauthorized");
    const roles = (roleRows ?? []).map((row: { role: string }) => row.role);
    // requiresMfa folds in the deployment-environment policy: every deployment
    // enforces MFA except one that has explicitly declared APP_ENV=demo.
    const mfaRequired = requiresMfa(roles);
    const assuranceLevel = assuranceLevelFromClaims(data.claims);
    if (!options.allowAal1 && mfaRequired && assuranceLevel !== "aal2") {
      throw new Error("MFA verification required");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
        roles,
        mfaRequired,
        assuranceLevel,
      },
    });
  });
}

export const requireSupabaseAuth = authMiddleware({ allowPasswordChange: false, allowAal1: false });
export const requireSupabaseAuthAllowPasswordChange = authMiddleware({
  allowPasswordChange: true,
  allowAal1: true,
});
export const requireSupabaseAuthAllowMfaChallenge = authMiddleware({
  allowPasswordChange: false,
  allowAal1: true,
});
